UNSET(C_TOOLS_ROOT)
UNSET(C_TOOLS_BIN)
UNSET(C_TOOLS_INC)
UNSET(C_TOOLS_LIB)

SET(C_TOOLS_ROOT ${PROJECT_SOURCE_DIR} CACHE PATH "c_tools root")
SET(C_TOOLS_BIN ${C_TOOLS_ROOT}/bin CACHE PATH "c_tools bin")
SET(C_TOOLS_INC ${C_TOOLS_ROOT}/include CACHE PATH "c_tools include")
SET(C_TOOLS_LIB ${C_TOOLS_ROOT}/lib CACHE PATH "c_tools library")

SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${C_TOOLS_LIB})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${C_TOOLS_LIB})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${C_TOOLS_BIN})

INCLUDE_DIRECTORIES(${C_TOOLS_INC})